version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: wordle_db
      POSTGRES_PASSWORD: wordle_password
      POSTGRES_USER: wordle_user
    volumes: 
      - dbdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    build:
      context: ~/Desktop/jump/projects/wordle/frontend
      dockerfile: Dockerfile
    environment:
      WORDLE__DB_HOST: db
      WORDLE__DB_NAME: wordle_db
      WORDLE__DB_USER: wordle_user
      WORDLE__DB_PASSWORD: wordle_password
    depends_on:
      db:
        condition: service_healthy

  server:
    build:
      context: ~/Desktop/jump/projects/wordle/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes: 
  dbdata:


