version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: wordle_db
      POSTGRES_PASSWORD: wordle_password
      POSTGRES_USER: wordle_user
    volumes: 
      - dbdata:/var/lib/postgresql/data
  # server:
  #   build:
  #     context: wordle
  #     dockerfile: Dockerfile
  #   environment:
  #     WHALEAPP__DB_HOST: db
  #     WHALEAPP__DB_NAME: wordle_db
  #     WHALEAPP__DB_USER: wordle_user
  #     WHALEAPP__DB_PASSWORD: wordle_password


volumes: 
  dbdata: